import { Inter } from "next/font/google";
import "./globals.css";
import ResponsiveDrawer from "@/components/sidebar";
import SidebarLayout from "@/components/sidebarLayout";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        
        <SidebarLayout/>
        <Box sx={{marginLeft:32}}>{children}
</Box>
          {/* </SidebarLayout> */}
        </body>
    </html>
  );
}
